# Generated by Django 4.1.3 on 2022-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_rename_numero_dni_familiar_numero_pasaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.CharField(max_length=200),
        ),
    ]
