# Generated by Django 4.1.3 on 2022-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_alter_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
            ],
        ),
    ]
